services:
  postgres:
    image: postgres:16
    container_name: postgres-aerobase
    restart: unless-stopped

    environment:
      POSTGRES_DB: aerobase
      POSTGRES_USER: aerobase_user
      POSTGRES_PASSWORD: aerobase_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
